name: Test
on:
  push:

defaults:
  run:
    shell: bash

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: ['8.2']
        wordpress: ['6.6.5', '6.7.5', '6.8.5', '6.9.4']
        mode: ['multi-site']
        include:
        - os: ubuntu-latest
          php: '8.3'
          wordpress: '6.8.5'
          mode: multi-site
        - os: ubuntu-latest
          php: '8.4'
          wordpress: '6.9.4'
          mode: multi-site
        - os: ubuntu-latest
          php: '8.5'
          wordpress: '6.9.4'
          mode: multi-site
        - os: ubuntu-latest
          php: '8.2'
          wordpress: '6.9.4'
          mode: single-site
    services:
      gcs:
        image: ghcr.io/mrhenry/fake-gcs-server
        ports:
          - 4443:4443
      mysql:
        image: mysql:8
        env:
          MYSQL_RANDOM_ROOT_PASSWORD: 1
          MYSQL_DATABASE: wp_tests_db
          MYSQL_USER: wp_test
          MYSQL_PASSWORD: password
          MYSQL_HOST: 127.0.0.1
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
    - uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # v2.36
      with:
        php-version: ${{ matrix.php }}
        extensions:
          imagick

    - name: create bucket
      run: |
        curl -X POST --data '{ "name": "test-bucket", "location": "US", "storageClass": "STANDARD", "iamConfiguration": { "uniformBucketLevelAccess": { "enabled": true } } }' \
        -H "Content-Type: application/json" \
        "http://0.0.0.0:4443/storage/v1/b"

    - name: install svn
      run: |
        sudo apt-get update
        sudo apt-get install -y subversion

    - name: checkout
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

    - name: install dependencies
      uses: php-actions/composer@8a65f0d3c6a1d17ca4800491a40b5756a4c164f3 # v6.1.2
      with:
        args: "--ignore-platform-reqs"

    - name: lint
      run: |
        ./vendor/bin/phpcs gs-uploads.php ./inc ./.tests

    - name: setup wordpress tests
      env:
        WP_VERSION: ${{ matrix.wordpress }}
        TMPDIR: ./.wp-test-root
      run: |
        bash .github/bin/install-wp-tests.sh wp_tests_db wp_test password 127.0.0.1 $WP_VERSION

    - name: test
      if: ${{ matrix.mode == 'single-site' }}
      env:
        GS_UPLOADS_BUCKET: test-bucket
        GS_UPLOADS_API_ENDPOINT: "http://0.0.0.0:4443"
      run: |
        ./vendor/bin/phpunit -c .phpunit-single-site.xml.dist

    - name: test
      if: ${{ matrix.mode == 'multi-site' }}
      env:
        GS_UPLOADS_BUCKET: test-bucket
        GS_UPLOADS_API_ENDPOINT: "http://0.0.0.0:4443"
      run: |
        ./vendor/bin/phpunit -c .phpunit-multi-site.xml.dist
